#!/bin/sh
########################################################################
# Begin xboxdrv
#
# Description : xboxdrv init script
#
# Author      : Name - name@linuxfromscratch.org
#
# Version     : BLFS 7.0
#
########################################################################

### BEGIN INIT INFO
# Provides:            xboxdrv
# Required-Start:      $network $syslog
# Required-Stop:       $network $syslog
# Default-Start:       2 3 4 5
# Default-Stop:        0 1 6
# Short-Description:   Starts xboxdrv.
# Description:         Starts xboxdrv daemon.
# X-LFS-Provided-By:   BLFS
### END INIT INFO

. /lib/lsb/init-functions

CONF=/etc/xboxdrv.conf
PID=/run/xboxdrv.pid
PROG=/usr/bin/xboxdrv

if [ -f $CONF ]; then
   . $CONF
fi

case "$1" in
   start)
      log_info_msg "Enabling Xboxdrv..."
      start_daemon -p $PID $PROG --daemon --detach --pid-file $PID $XBOXDRV_OPTS  &
      evaluate_retval
      ;;

   stop)
      log_info_msg "Removing Xboxdrv..."
      killproc -p $PID $PROG
      evaluate_retval
      ;;

   restart)
      $0 stop
      sleep 1
      $0 start
      ;;

   status)
       statusproc $PROG
       evaluate_retval
      ;;

   *)
      echo "Usage: $0 {start|stop|restart|status}"
      exit 1
      ;;
esac

# End /etc/init.d/seatd
