#!/bin/sh
#   
# pkgadd - Package install utility
# POSIX-compliant shell script for install, reinstall or upgrade packages
#

trap "interrupted" 1 2 3 15

export LC_ALL=C.UTF-8

# Function to safely get the absolute physical path (POSIX replacement for 'realpath')
get_realpath() {
    # If the argument is a directory, just use cd -P and pwd -P
    [ -d "$1" ] && { CDPATH= cd -P -- "$1" && pwd -P; return; }
    
    # Otherwise, handle it as a file
    dir=$(dirname -- "$1")
    base=$(basename -- "$1")
    # Use a subshell to avoid changing the current directory permanently
    (CDPATH= cd -P -- "$dir" && printf '%s/%s\n' "$(pwd -P)" "$base")
}

interrupted() {
    printf '\n'
    ret 1
}

msg() {
    printf "==> %s\n" "$1"
}

msgerr() {
    printf "ERROR: %s\n" "$1" >&2
}

help() {
    cat << 'EOF'
Usage:
  pkgadd [ <options> <package.spkg.txz> ]

Options:
  -u, --upgrade              upgrade package
  -r, --reinstall            reinstall package
  -c, --ignore-conflict      ignore conflict when installing package
  -v, --verbose              print files installed
  -h, --help                 show this help message
      --no-backup            skip backup when upgrading package
      --print-dbdir          print package database path
      --root=<path>          install to custom root directory
      
EOF
}

# Function to extract long options into separate short/long options for easier parsing
extract_opts() {
    while [ $# -gt 0 ]; do
        arg=$1
        case "$arg" in
            --*) opts="$opts $arg";;
            -?*) rest=${arg#-}
                 while [ -n "$rest" ]; do
                    chr="${rest%"${rest#?}"}"
                    opts="$opts -$chr"
                    rest=${rest#?}
                 done
                 ;;
            *) opts="$opts $arg";;
        esac
        shift
    done
    printf '%s\n' "${opts# }"
}

parse_opts() {
    if [ -z "$1" ]; then
        SHOWHELP=yes
    else
        while [ -n "$1" ]; do
            case $1 in
                -u | --upgrade)         UPGRADE_PKG=yes ;;
                -r | --reinstall)       REINSTALL_PKG=yes ;;
                -c | --ignore-conflict) IGNORE_CONFLICT=yes ;;
                -v | --verbose)         VERBOSE_INSTALL="yes" ;; 
                -h | --help)            SHOWHELP=yes ;;
                     --no-backup)       NO_BACKUP=yes ;;
                     --print-dbdir)     PRINTDBDIR=yes ;;
                     --root=*)          ROOT_DIR="${1#*=}" ;;
                     *.spkg.tar.*)      PKGNAME="$(get_realpath "$1")" ;;
                     *)                 msg "Invalid option! ($1)"; exit 1 ;;
            esac
            shift
        done
    fi
}

ret() {
    # Remove lock and all tmp files on exit
    rm -f "$ROOT_DIR/$LOCK_FILE" "$TMP_PKGADD" "$TMP_PKGINSTALL" "$TMP_CONFLICT"
    exit "$1"
}

isinstalled() {
    if [ -s "$ROOT_DIR/$PKGDB_DIR/$1" ]; then
        return 0
    else
        return 1
    fi
}

# Process options
parse_opts $(extract_opts "$@")

SCRATCHPKG_DIR="var/lib/scratchpkg"
PKGDB_DIR="$SCRATCHPKG_DIR/db"
LOCK_FILE="$SCRATCHPKG_DIR/spkg.lock"

ROOT_DIR="${ROOT_DIR%/}" # Remove trailing slash

[ "$PRINTDBDIR" ] && {
    printf '%s/%s\n' "$ROOT_DIR" "$PKGDB_DIR"
    exit 0
}

# Show help page
if [ "$SHOWHELP" ] || [ -z "$PKGNAME" ]; then
    help
    exit 0
fi

[ -d "$ROOT_DIR/$PKGDB_DIR" ] || {
    msgerr "Package's database directory does not exist: $ROOT_DIR/$PKGDB_DIR"
    exit 1
}

# Check for root access
[ "$(id -u)" = "0" ] || {
    msgerr "Installing packages requires root access!"
    help
    exit 1
}

# Check for lock file
[ -f "$ROOT_DIR/$LOCK_FILE" ] && {
    msgerr "Cannot install/remove package simultaneously."
    msgerr "remove '$ROOT_DIR/$LOCK_FILE' if no install/remove package process running."
    exit 1
}

touch "$ROOT_DIR/$LOCK_FILE" 2>/dev/null || {
    msgerr "Cannot create lock file in '$ROOT_DIR/$LOCK_FILE'."
    exit 1
}

BASEPKGNAME=$(basename "$PKGNAME")

# Check existence of package file
[ -f "$PKGNAME" ] || {
    msgerr "Package '$1' does not exist!"
    ret 1
}

noextname=${BASEPKGNAME%*.spkg.tar.*}
release=${noextname##*-}
noextname=${noextname%-*}
version=${noextname##*-}
name=${noextname%-*}

# Get package information if installed
if isinstalled "$name"; then
    iversion=$(awk 'NR==1 {print $1}' "$ROOT_DIR/$PKGDB_DIR/$name")
    irelease=$(awk 'NR==1 {print $2}' "$ROOT_DIR/$PKGDB_DIR/$name")
    ALREADYINSTALLED=yes
fi

if [ "$ALREADYINSTALLED" = "yes" ] && [ ! "$UPGRADE_PKG" ] && [ ! "$REINSTALL_PKG" ]; then
    printf "Package '%s' already installed. (%s-%s)\n" "$name" "$iversion" "$irelease"
    ret 0
fi

# Can't reinstall if not installed and can't upgrade if up-to-date
if [ "$UPGRADE_PKG" ] || [ "$REINSTALL_PKG" ]; then   
    if [ "$ALREADYINSTALLED" != "yes" ]; then
        msgerr "Package '$name' not installed."
        ret 1
    fi
    if [ "$UPGRADE_PKG" ]; then   
        if [ "$version-$release" = "$iversion-$irelease" ]; then
            printf "Package '%s' is up-to-date. (%s-%s)\n" "$name" "$iversion" "$irelease"
            ret 0
        fi
    fi
fi

TMP_PKGADD="$ROOT_DIR/$SCRATCHPKG_DIR/.tmp_pkgadd"
TMP_PKGINSTALL="$ROOT_DIR/$SCRATCHPKG_DIR/.tmp_pkginstall"
TMP_CONFLICT="$ROOT_DIR/$SCRATCHPKG_DIR/.tmp_conflict"

# Check integrity of package and save list file/dirs to install
# Note: POSIX 2024 standardized 'tar'. Flags are compliant.
LC_ALL=en_US.UTF-8 \
tar -tvf "$PKGNAME" > "$TMP_PKGADD" 2>/dev/null || {
    msgerr "Package '$1' is corrupted!"
    ret 1
}
# Set operation whether install/upgrade/reinstall
opr=install
[ "$UPGRADE_PKG" ] && opr=upgrade
[ "$REINSTALL_PKG" ] && opr=reinstall
printf "%s: %s-%s-%s...\n" "$opr" "$name" "$version" "$release"

# Check for file conflict
if [ ! "$IGNORE_CONFLICT" ]; then
    grep -v '/$' "$TMP_PKGADD" | awk '{print $6}' | while read -r line; do
        if [ "$line" = "${line%.*}.spkgnew" ]; then
            line=${line%.*}
        fi
        if [ -e "$ROOT_DIR/$line" ] || [ -L "$ROOT_DIR/$line" ]; then
            if [ "$UPGRADE_PKG" ] || [ "$REINSTALL_PKG" ]; then
                if ! grep -Fqx "$line" "$ROOT_DIR/$PKGDB_DIR/$name"; then
                    _f=$(grep -x "^$line$" "$ROOT_DIR/$PKGDB_DIR"/* | cut -d : -f1 | awk -F / '{print $(NF)}' | head -n1 | grep -vx "$name")
                    _f=${_f:-(none)}
                    printf '%s %s\n' "$_f" "$line"
                    touch "$TMP_CONFLICT"
                fi
            else
                _f=$(grep -x "^$line$" "$ROOT_DIR/$PKGDB_DIR"/* | cut -d : -f1 | awk -F / '{print $(NF)}' | head -n1)
                _f=${_f:-(none)}
                printf '%s %s\n' "$_f" "$line"
                touch "$TMP_CONFLICT"
            fi
        fi
    done
	
    if [ -e "$TMP_CONFLICT" ]; then
        msgerr "File conflict found! $name"
        ret 1
    fi
fi

rm -f "$TMP_PKGINSTALL"

# Extract package into ROOT_DIR
# Replaced 'cp --reflink=auto' (GNU extension) with 'cp -f' (POSIX compatible)
tar -xvhpf "$PKGNAME" -C "$ROOT_DIR"/ | while read -r line; do
    if [ "$line" = "${line%.*}.spkgnew" ]; then
        line=${line%.*}
        if [ "$UPGRADE_PKG" ] || [ "$REINSTALL_PKG" ]; then
            if [ ! -e "$ROOT_DIR/$line" ] || [ "$NO_BACKUP" = yes ]; then
                cp -f "$ROOT_DIR/$line".spkgnew "$ROOT_DIR/$line"
                rm -f "$ROOT_DIR/"*.spkgnew
            fi
        else
            cp -f "$ROOT_DIR/$line".spkgnew "$ROOT_DIR/$line"
            rm -f "$ROOT_DIR/"*.spkgnew
        fi
    fi
    [ "$VERBOSE_INSTALL" ] && printf "extracted '%s'\n" "$line"
    printf '%s\n' "$line" >> "$TMP_PKGINSTALL"
done

# Remove old files from old package that do not exist in new package
if [ "$UPGRADE_PKG" ] || [ "$REINSTALL_PKG" ]; then
	# awk replacement for tail + tac (no POSIX)
	awk 'NR>1 { lines[n++] = $0 } END { while (n--) print lines[n] }' \
	    "$ROOT_DIR/$PKGDB_DIR/$name" | while read -r line; do
        case $line in
            */[) ;;
            */) # Directory removal logic
                if grep "^$line$" "$ROOT_DIR/$PKGDB_DIR"/* "$TMP_PKGINSTALL" 2>/dev/null | grep -qv "$ROOT_DIR/$PKGDB_DIR/$name"; then
                     : # Do nothing if directory is used by another package
                else
                     # Manual verbose printing, as 'rmdir -v' is not POSIX
                     if [ "$VERBOSE_INSTALL" ]; then printf "removing directory '%s'\n" "$ROOT_DIR/$line"; fi
                     rmdir "$ROOT_DIR/$line" 2>/dev/null
                fi
                ;;
            *)  # File removal logic
                if ! grep -q "^$line$" "$TMP_PKGINSTALL"; then
                     # Manual verbose printing, as 'rm -v' is not POSIX
                     if [ "$VERBOSE_INSTALL" ]; then printf "removing '%s'\n" "$ROOT_DIR/$line"; fi
                     rm -f "$ROOT_DIR/$line"
                fi
                ;;
        esac
    done
fi

# Register package into database
# Use printf for safe output of version and release strings
printf '%s %s\n' "$version" "$release" > "$ROOT_DIR/$PKGDB_DIR/$name"
cat "$TMP_PKGINSTALL" >> "$ROOT_DIR/$PKGDB_DIR/$name"

# Running ldconfig
if [ -x "$ROOT_DIR"/sbin/ldconfig ]; then
    "$ROOT_DIR"/sbin/ldconfig -r "$ROOT_DIR"/
fi

ret 0
