#
# Configuration file for scratchpkg
#

#export CFLAGS="-pipe -march=native -O2 -fasynchronous-unwind-tables -flto=auto -fuse-linker-plugin"
#export CXXFLAGS="${CFLAGS}"

export jobs=10
export MAKEFLAGS="-j${jobs}"
export NINJAJOBS="${jobs}"
export CPULIST="0-9"

export LTOFLAGS="-flto=auto"
export LTOFLAGSCC="-ffat-lto-objects -flto=auto "

#export MMARCH="x86-64-v3"
export MMARCH="native"
export MTUNE="generic"

export CFLAGS=" -O2 -g -feliminate-unused-debug-types -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=64 -Wformat -Wformat-security -Wl,-z,now,-z,relro,-z,max-page-size=0x4000,-z,separate-code -Wno-error -ftree-vectorize -ftree-slp-vectorize -Wl,--enable-new-dtags  -Wl,--build-id=sha1  -ftrivial-auto-var-init=zero -mrelax-cmpxchg-loop -gz -ffunction-sections -m64 -fasynchronous-unwind-tables -Wp,-D_REENTRANT -fPIC -march=$MMARCH "
export CXXFLAGS=" $CFLAGS "
export FFLAGS=" -O3 -feliminate-unused-debug-types -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -m64 -fasynchronous-unwind-tables -Wp,-D_REENTRANT -ftree-loop-distribute-patterns -Wl,-z,now -Wl,-z,relro -malign-data=abi -fno-semantic-interposition -ftree-vectorize -ftree-loop-vectorize -Wl,--enable-new-dtags -ffunction-sections "
export FCFLAGS="$FFLAGS"
export LDFLAGS="-Wl,-O1,--as-needed  -Wl,--build-id=sha1"

export DEBUGFLAGS=""
#export DEBUGFLAGS=" -fdebug-types-section -femit-struct-debug-baseonly -g1 -gno-column-info -gno-variable-location-views -gz=zstd "

export RUSTFLAGS="-C opt-level=2 -C target-cpu=$MMARCH"

SOURCE_DIR="/sources/src"
PACKAGE_DIR="/sources/packages"
WORK_DIR="/sources/work"
# PACKAGE_DIR="/var/cache/scratchpkg/packages"
# WORK_DIR="/var/cache/scratchpkg/work"
# CURL_OPTS=""
COMPRESSION_MODE="xz"
#NO_STRIP="no"
IGNORE_CHECKSUM="yes"
# KEEP_LIBTOOL="no"
KEEP_LOCALE="yes"
KEEP_DOC="yes"
BUILD_PGO="yes"
# NOCOLOR="no"
DO_DEBUG="yes"


# samba mariadb openldap krb5 gstreamer unixodbc postgresql
# apache php
export OPT_DEPLISTS="
appindicator brotli cddb dvd faad gtk3 libnotify libsecret 
semantic-desktop "

export MODULE_SIGNING="yes"

export BOOTBLFS="20240209"
export SOURCE_DATE_EPOCH=1701580000
