# Default config version
config_version	1.2

# So the hard disk is not polluted in case the backup filesystem is not available
no_create_root	1

# Standard settings
cmd_cp			/bin/cp
cmd_rm			/bin/rm
cmd_rsync		/usr/bin/rsync
link_dest		1

rsync_long_args	-evaAX --numeric-ids

# Store all backups in one directory per machine
# A useful alternative may be to create a separate directory for each interval
snapshot_root	/mnt/other/source/BACKRNSAP/

# increments, which are kept
retain	daily	7
retain	weekly	4
retain	monthly	12

# Exclude pattern (refer to --exclude-from from rsync man page)
exclude	/dev/*
exclude	/proc/*
exclude	/sys/*
exclude	/run/*
exclude	/var/tmp/*
exclude	/var/run/*
exclude	/tmp/*
exclude	/lost+found
exclude	/mnt/*/*
exclude	/sources/packages/*
exclude	/sources/ports/*
exclude	/sources/src/*
exclude	/sources/work/*
exclude	/sources/FAKEROOT/*
exclude	/boot/efi/*
exclude	/boot/grub/*


# Backup folder(s)/files
backup	/	localhost/
