#!/bin/bash

usage() {
	cat <<-__EOF__
		usage: setup <install> [plasma|xfce|hyprland|rofi]

        optional: install 
            install [plasma|xfce|hyprland|wayfire|steam]

		write xinitrc file in HOME
        and create ~/.cache folder

        rofi:
         cp dotfiles config to .config.rofi

		
		help  Show this help

	__EOF__
	exit $1
}

writehome() {
    echo "$1" > ~/.xinitrc 
}

doinstall() {
    case $1 in
        xfce)
            scratch -I -y -f  xfce xarchiver xfce4-screenshooter rofi mousepad mpv
            scratch -I -y -f  vscodium-bin unbound
            scratch -I -y -f  ttf-nerd-fonts-symbols eww eww-xfce-dots
            ;;
        wayfire)
            scratch -I -y -f  wayfire-meta wmctrl wofi
            ;;
        steam)
            scratch -I -y -f  steam umu-launcher protontricks
            ;;
        *)
            usage ; exit 0
            ;;
    esac
    exit
}


if [[ $EUID -eq 0 ]]; then
    echo "This script must be NOT run as root" 1>&2
    exit 1
fi

[ ! -d ~/.cache ] && mkdir -p ~/.cache 

case $1 in
    xfce)
        writehome "dbus-launch --exit-with-x11 startxfce4"
        ;;
    plasma)
        writehome "dbus-launch --exit-with-x11 /usr/bin/startplasma-x11"
        ;;
    rofi)
        mkdir -p ~/.config/rofi
        if scratch isinstalled rofi-dotfiles;then
            cp -r /usr/local/share/rofi/* ~/.config/rofi/
        else
            echo "rofi-dotfiles not installed"
        fi
        ;;
    help)
        usage ; exit 0
        ;;
    install)
        doinstall $2; exit 0
        ;;
    *)
        usage ; exit 0
        ;;
esac

