#!/bin/bash

usage() {
	cat <<-__EOF__
		usage: setup <install> [plasma|xfce|xfcewayland]

        optional: install 
            install [plasma|xfce|hyprland|wayfire|steam]

		options:
			help  Show this help

		xfcewayland:
		    write xfce-wayland.sh to launch xfce with wayfire
		other:
		    write xinitrc file in HOME
		    and create ~/.cache folder
	__EOF__
	exit $1
}

writehome() {
    echo "$1" > ~/.xinitrc 
}

doinstall() {
    case $1 in
        xfce)
            scratch -I -y -f  xfce xarchiver xfce4-screenshooter rofi mousepad mpv
            scratch -I -y -f  vscodium-bin unbound
            scratch -I -y -f  ttf-nerd-fonts-symbols eww eww-xfce-dots
            ;;
        wayfire)
            scratch -I -y -f  wayfire-meta wmctrl wofi
            ;;
        steam)
            scratch -I -y -f  steam umu-launcher protontricks
            ;;
        *)
            usage ; exit 0
            ;;
    esac
    exit
}

if [[ $EUID -eq 0 ]]; then
    echo "This script must be NOT run as root" 1>&2
    exit 1
fi

[ ! -d ~/.cache ] && mkdir -p ~/.cache 


case $1 in
    xfce)
        writehome "dbus-launch --exit-with-x11 startxfce4"
        ;;
	xfcewayland)
		cat > ~/xfce-wayland.sh << "EOF"
#!/bin/sh

  startxfce4 --wayland wayfire
EOF
		chmod +x ~/xfce-wayland.sh
		;;
    plasma)
        writehome "dbus-launch --exit-with-x11 /usr/bin/startplasma-x11"
        ;;
    help)
        usage ; exit 0
        ;;
    install)
        doinstall $2; exit 0
        ;;
    *)
        usage ; exit 0
        ;;
esac

