#!/bin/sh
########################################################################
# Begin wg-netns
#
# Description : lact init script
#
# Author      : Name - name@linuxfromscratch.org
#
# Version     : BLFS 7.0
#
########################################################################

### BEGIN INIT INFO
# Provides:            lact
# Required-Start:      $network $syslog
# Required-Stop:       $network $syslog
# Default-Start:       2 3 4 5
# Default-Stop:        0 1 6
# Short-Description:   Starts lact.
# Description:         Starts lact daemon.
# X-LFS-Provided-By:   BLFS
### END INIT INFO

. /lib/lsb/init-functions

PID=/run/lact.pid
PROG=/usr/bin/lact
OPTS="daemon"
LOG=/var/log/lact.log

case "$1" in
   start)
      log_info_msg "Enabling Lact..."
      start_daemon -p $PID $PROG $OPTS >> $LOG 2>&1 &
      evaluate_retval
      ;;

   stop)
      log_info_msg "Removing Lact..."
      killproc -p $PID $PROG
      evaluate_retval
      ;;

   restart)
      $0 stop
      sleep 1
      $0 start
      ;;

   status)
       statusproc $PROG
       evaluate_retval
      ;;

   *)
      echo "Usage: $0 {start|stop|restart|status}"
      exit 1
      ;;
esac

# End /etc/init.d/seatd
