#!/bin/sh
########################################################################
# Begin fcron
#
# Description : Dinit init script
#
# Author      : Name - name@linuxfromscratch.org
#
# Version     : BLFS 7.0
#
########################################################################

### BEGIN INIT INFO
# Provides:          dinit
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start dinit service manager
# Description:         Starts dinit daemon.
### END INIT INFO

. /lib/lsb/init-functions

BIN_FILE="/usr/sbin/dinit"

case "$1" in
  start)
    log_info_msg "Starting Dinit..."
    start_daemon ${BIN_FILE}
	evaluate_retval
    ;;

  stop)
    log_info_msg "Stopping Dinit..."
    killall ${BIN_FILE}
	evaluate_retval
    ;;

  restart)
    $0 stop
    sleep 1
    $0 start
    ;;

   status)
      statusproc ${BIN_FILE}
      ;;
  *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
esac

# End /etc/init.d/dinit
