#!/bin/sh

if [[ $EUID -eq 0 ]]; then
    echo "This script must be NOT run as root" 1>&2
    exit 1
fi

cd $HOME

mkdir -pv $HOME/.config/wofi $HOME/Documents

cp -r /usr/local/share/wayfire/* $HOME/.config/

cp -r /usr/local/share/wofi/* $HOME/.config/
